package lib

import (
	"math/rand"
	"time"
)

/*
Function that returns a random word from a string table dic
*/

func ChoseRandomWord(dic []string) string {
	return dic[rand.New(rand.NewSource(time.Now().UnixNano())).Intn(len(dic))] // index number generated by the function rand using time as a seed and ranged between 0 and dic's length
}
